I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00images.rpy", line 55, in script
    init python:
  File "renpy/common/00images.rpy", line 58, in <module>
    _scan_images_directory()
  File "renpy/common/00images.rpy", line 53, in _scan_images_directory
    renpy.image(base, fn)
Exception: Unknown image modifier '70-129-scaled' in 'images/AD24-Full-Album-@70-129-scaled.jpg'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00images.rpy", line 55, in script
    init python:
  File "C:\Users\idaduser\Downloads\renpy-8.3.2-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\idaduser\Downloads\renpy-8.3.2-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00images.rpy", line 58, in <module>
    _scan_images_directory()
  File "renpy/common/00images.rpy", line 53, in _scan_images_directory
    renpy.image(base, fn)
  File "C:\Users\idaduser\Downloads\renpy-8.3.2-sdk\renpy\exports\displayexports.py", line 73, in image
    d = renpy.easy.displayable(d)
  File "C:\Users\idaduser\Downloads\renpy-8.3.2-sdk\renpy\easy.py", line 128, in displayable
    return renpy.store.Image(d)
  File "C:\Users\idaduser\Downloads\renpy-8.3.2-sdk\renpy\display\im.py", line 2035, in image
    return Image(arg, **properties)
  File "C:\Users\idaduser\Downloads\renpy-8.3.2-sdk\renpy\display\im.py", line 715, in __init__
    raise Exception("Unknown image modifier %r in %r." % (i, filename))
Exception: Unknown image modifier '70-129-scaled' in 'images/AD24-Full-Album-@70-129-scaled.jpg'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
Dingle Visual Novel 1.0
Tue Feb 18 13:48:32 2025
